[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/auth-me"
  status = 200

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200

[[redirects]]
  from = "/api/auth/activate"
  to = "/.netlify/functions/auth-activate"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/admin/dashboard"
  to = "/.netlify/functions/admin-dashboard"
  status = 200

[[redirects]]
  from = "/api/admin/employee-import"
  to = "/.netlify/functions/admin-employee-import"
  status = 200

[[redirects]]
  from = "/api/admin/employee-reset-password"
  to = "/.netlify/functions/admin-employee-reset-password"
  status = 200

[[redirects]]
  from = "/api/admin/employee-active"
  to = "/.netlify/functions/admin-employee-active"
  status = 200

[[redirects]]
  from = "/api/admin/employee-update"
  to = "/.netlify/functions/admin-employee-update"
  status = 200

[[redirects]]
  from = "/api/admin/employee-delete"
  to = "/.netlify/functions/admin-employee-delete"
  status = 200
